-- V3 FINAL TEST: leaderboard + chat + 2026.09.13 final tournament (Mongolia UTC+8)
-- Run this whole file in Supabase SQL Editor.

create or replace function public.get_leaderboard()
returns table (rank_number bigint, player_username text, player_display_name text, player_xp integer, player_unlocked integer)
language sql security definer set search_path=public as $$
 select row_number() over(order by p.xp desc,p.created_at asc),p.username,p.display_name,p.xp,p.unlocked
 from public.profiles p where p.is_active=true order by p.xp desc,p.created_at asc limit 100;
$$;
grant execute on function public.get_leaderboard() to authenticated;

create table if not exists public.chat_messages(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,display_name text not null,message text not null check(char_length(message) between 1 and 250),created_at timestamptz not null default now());
alter table public.chat_messages enable row level security;
drop policy if exists "chat read active" on public.chat_messages; create policy "chat read active" on public.chat_messages for select to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_active));
drop policy if exists "chat insert own active" on public.chat_messages; create policy "chat insert own active" on public.chat_messages for insert to authenticated with check(user_id=auth.uid() and exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_active));
do $$ begin alter publication supabase_realtime add table public.chat_messages; exception when duplicate_object then null; end $$;

create table if not exists public.final_questions(question_no int primary key check(question_no between 1 and 10),question text not null,option_a text not null,option_b text not null,option_c text not null,option_d text not null,correct_option text not null check(correct_option in('A','B','C','D')),updated_at timestamptz default now());
create table if not exists public.final_attempts(user_id uuid primary key references auth.users(id) on delete cascade,started_at timestamptz not null default now(),finished_at timestamptz,correct_count int not null default 0,wrong_count int not null default 0,answered_count int not null default 0,elapsed_ms bigint not null default 0);
create table if not exists public.final_answers(user_id uuid references auth.users(id) on delete cascade,question_no int references public.final_questions(question_no),answer text not null,correct boolean not null,elapsed_ms bigint not null,created_at timestamptz default now(),primary key(user_id,question_no));
alter table public.final_questions enable row level security; alter table public.final_attempts enable row level security; alter table public.final_answers enable row level security;

create or replace function public.get_final_questions() returns table(question_no int,question text,option_a text,option_b text,option_c text,option_d text)
language plpgsql security definer set search_path=public as $$ begin
 if now() < timestamptz '2026-09-13 17:00:00+08' or now() >= timestamptz '2026-09-13 17:30:00+08' then raise exception 'Тэмцээнд орох хугацаа биш байна.'; end if;
 return query select q.question_no,q.question,q.option_a,q.option_b,q.option_c,q.option_d from public.final_questions q order by q.question_no;
end $$;

create or replace function public.join_final_tournament() returns jsonb language plpgsql security definer set search_path=public as $$ declare a public.final_attempts; begin
 if auth.uid() is null then raise exception 'Нэвтрээгүй байна.'; end if;
 if now() < timestamptz '2026-09-13 17:00:00+08' or now() >= timestamptz '2026-09-13 17:30:00+08' then raise exception '17:00–17:30 хооронд оролцоно.'; end if;
 if (select count(*) from public.final_questions)<>10 then raise exception '10 асуулт бүрэн оруулаагүй байна.'; end if;
 select * into a from public.final_attempts where user_id=auth.uid();
 if found then return jsonb_build_object('already_finished',a.finished_at is not null,'answered_count',a.answered_count,'correct_count',a.correct_count,'wrong_count',a.wrong_count,'elapsed_ms',a.elapsed_ms); end if;
 insert into public.final_attempts(user_id) values(auth.uid()) returning * into a;
 return jsonb_build_object('already_finished',false,'answered_count',0,'correct_count',0,'wrong_count',0,'elapsed_ms',0);
end $$;

create or replace function public.submit_final_answer(p_question_no int,p_answer text,p_elapsed_ms bigint) returns jsonb language plpgsql security definer set search_path=public as $$ declare ok boolean; a public.final_attempts; begin
 if now() >= timestamptz '2026-09-13 17:30:00+08' then raise exception 'Тэмцээн хаагдсан.'; end if;
 select * into a from public.final_attempts where user_id=auth.uid() for update;
 if not found or a.finished_at is not null then raise exception 'Идэвхтэй оролдлого алга.'; end if;
 if exists(select 1 from public.final_answers where user_id=auth.uid() and question_no=p_question_no) then raise exception 'Энэ асуултад аль хэдийн хариулсан.'; end if;
 select upper(p_answer)=q.correct_option into ok from public.final_questions q where q.question_no=p_question_no;
 if ok is null then raise exception 'Асуулт олдсонгүй.'; end if;
 insert into public.final_answers values(auth.uid(),p_question_no,upper(p_answer),ok,greatest(0,p_elapsed_ms),now());
 update public.final_attempts set correct_count=correct_count+case when ok then 1 else 0 end,wrong_count=wrong_count+case when ok then 0 else 1 end,answered_count=answered_count+1,elapsed_ms=greatest(elapsed_ms,greatest(0,p_elapsed_ms)) where user_id=auth.uid();
 return jsonb_build_object('correct',ok);
end $$;

create or replace function public.finish_final_tournament(p_elapsed_ms bigint) returns void language plpgsql security definer set search_path=public as $$ begin
 update public.final_attempts set finished_at=coalesce(finished_at,now()),elapsed_ms=greatest(elapsed_ms,greatest(0,p_elapsed_ms)) where user_id=auth.uid() and finished_at is null;
end $$;

create or replace function public.get_final_results() returns table(player_display_name text,correct_count int,wrong_count int,elapsed_ms bigint)
language plpgsql security definer set search_path=public as $$ begin
 if now() < timestamptz '2026-09-13 17:40:00+08' then raise exception 'Эцсийн дүн 17:40-д гарна.'; end if;
 return query select p.display_name,a.correct_count,a.wrong_count,a.elapsed_ms from public.final_attempts a join public.profiles p on p.id=a.user_id where a.finished_at is not null order by a.correct_count desc,a.elapsed_ms asc,a.finished_at asc;
end $$;

create or replace function public.admin_get_final_questions() returns setof public.final_questions language plpgsql security definer set search_path=public as $$ begin
 if not exists(select 1 from public.admin_users where user_id=auth.uid()) then raise exception 'Admin эрхгүй'; end if; return query select * from public.final_questions order by question_no;
end $$;
create or replace function public.admin_save_final_question(p_question_no int,p_question text,p_option_a text,p_option_b text,p_option_c text,p_option_d text,p_correct_option text) returns void language plpgsql security definer set search_path=public as $$ begin
 if not exists(select 1 from public.admin_users where user_id=auth.uid()) then raise exception 'Admin эрхгүй'; end if;
 if p_question_no not between 1 and 10 or upper(p_correct_option) not in('A','B','C','D') then raise exception 'Буруу утга'; end if;
 insert into public.final_questions(question_no,question,option_a,option_b,option_c,option_d,correct_option,updated_at) values(p_question_no,trim(p_question),trim(p_option_a),trim(p_option_b),trim(p_option_c),trim(p_option_d),upper(p_correct_option),now()) on conflict(question_no) do update set question=excluded.question,option_a=excluded.option_a,option_b=excluded.option_b,option_c=excluded.option_c,option_d=excluded.option_d,correct_option=excluded.correct_option,updated_at=now();
end $$;

revoke all on function public.get_final_questions() from public; revoke all on function public.join_final_tournament() from public; revoke all on function public.submit_final_answer(int,text,bigint) from public; revoke all on function public.finish_final_tournament(bigint) from public; revoke all on function public.get_final_results() from public;
grant execute on function public.get_final_questions() to authenticated; grant execute on function public.join_final_tournament() to authenticated; grant execute on function public.submit_final_answer(int,text,bigint) to authenticated; grant execute on function public.finish_final_tournament(bigint) to authenticated; grant execute on function public.get_final_results() to authenticated; grant execute on function public.admin_get_final_questions() to authenticated; grant execute on function public.admin_save_final_question(int,text,text,text,text,text,text) to authenticated;
